apiVersion: v1
kind: Service
metadata:
    name: "codeacademy2020cluster-041d"
    labels:
        app: "codeacademy2020cluster-041d"
spec:
    type: ClusterIP
    ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
    selector:
        app: "codeacademy2020cluster-041d"