apiVersion: v1
kind: Service
metadata:
  name: "codeacademy2020cluster-be43"
  labels:
    app: "codeacademy2020cluster-be43"
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: "codeacademy2020cluster-be43"
---
apiVersion: v1
kind: Service
metadata:
  name: "codeacademy2020mongo"
  labels:
    app: "codeacademy2020mongo"
spec:
  ports:
    - port: 27017
      name: mongo
  selector:
    app: "codeacademy2020mongo"
